---

esphome:
  name: "test_device"
  comment: "Test: Energy meter data from Modbus RTU to Wifi by ESPhome"
#  on_boot:
#    - lambda: |-
#        id(my_ota).set_auth_password("new-passwd");


# Setup RTU communication between ESP and Energy meter
uart:
  id: uart_modbus0
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  data_bits: 8
  stop_bits: 1
  parity: NONE

# Setup Modbus RTU configuration at configured UART
modbus:
  id: modbus0
  uart_id: uart_modbus0
  send_wait_time: 250ms

# Setup Modbus RTU devices (energy meter)
modbus_controller:
  - id: modbus_controller_pm1
    address: 1
    modbus_id: modbus0
    command_throttle: 100ms
    update_interval: 60s
    setup_priority: -10
  - id: modbus_controller_pm5
    address: 5
    modbus_id: modbus0
    command_throttle: 100ms
    update_interval: 30s
    setup_priority: -10


packages:
  device_default: !include
    file: "./Devices/8266_nodemcuv2.yaml"

  modbus_pm1_sdm72dm_v2_phases: !include
    file: "./SDM72DM-V2/3phase.yaml"
    vars:
      modbus_controller_id: modbus_controller_pm1
      power_meter_id: pm1
      power_meter_name: PM1-House

  modbus_pm1__sdm72dm_v2total: !include
    file: "./SDM72DM-V2/total.yaml"
    vars:
      modbus_controller_id: modbus_controller_pm1
      power_meter_id: pm1
      power_meter_name: PM1-House

  modbus_pm5_sdm72dm_v2_total: !include
    file: "./SDM72DM-V2/total.yaml"
    vars:
      modbus_controller_id: modbus_controller_pm5
      power_meter_id: pm5
      power_meter_name: PM5-Heating
