## Power meter: SDM72DM-V2 3 Phases voltage(LN, LL), current(I), power(P,Q,S)
#
# Modbus RTU (rs485)
#
# vars:
#
#   - modbus_controller_id
#   - power_meter_id
#   - power_meter_name
#


<<: !include ../units.yaml 


sensor:
# ---------------------------- Phase voltage LN ------------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_L1N
    name: ${power_meter_name_2}-L1N
    address: 0x0000
    unit_of_measurement: $unit_voltage
    device_class: "voltage"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_L2N
    name: ${power_meter_name_2}-L2N
    address: 0x0002
    unit_of_measurement: $unit_voltage
    device_class: "voltage"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_L3N
    name: ${power_meter_name_2}-L3N
    address: 0x0004
    unit_of_measurement: $unit_voltage
    device_class: "voltage"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
# ---------------------------- Phase current ---------------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_I1
    name: ${power_meter_name_2}-I1
    address: 0x0006
    unit_of_measurement: $unit_current
    device_class: "current"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_I2
    name: ${power_meter_name_2}-I2
    address: 0x0008
    unit_of_measurement: $unit_current
    device_class: "current"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_I3
    name: ${power_meter_name_2}-I3
    address: 0x000A
    unit_of_measurement: $unit_current
    device_class: "current"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
# ---------------------------- Phase active power ----------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_P1
    name: ${power_meter_name_2}-P1
    address: 0x000C
    unit_of_measurement: $unit_power_active
    device_class: "power"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_P2
    name: ${power_meter_name_2}-P2
    address: 0x000E
    unit_of_measurement: $unit_power_active
    device_class: "power"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_P3
    name: ${power_meter_name_2}-P3
    address: 0x0010
    unit_of_measurement: $unit_power_active
    device_class: "power"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
# ---------------------------- Phase apparent power --------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_S1
    name: ${power_meter_name_2}-S1
    address: 0x0012
    unit_of_measurement: $unit_power_apparent
    device_class: "apparent_power"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_S2
    name: ${power_meter_name_2}-S2
    address: 0x0014
    unit_of_measurement: $unit_power_apparent
    device_class: "apparent_power"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_S3
    name: ${power_meter_name_2}-S3
    address: 0x0016
    unit_of_measurement: $unit_power_apparent
    device_class: "apparent_power"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
# ---------------------------- Phase reactive power --------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_Q1
    name: ${power_meter_name_2}-Q1
    address: 0x0018
    unit_of_measurement: $unit_power_reactive
    device_class: "reactive_power"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_Q2
    name: ${power_meter_name_2}-Q2
    address: 0x001A
    unit_of_measurement: $unit_power_reactive
    device_class: "reactive_power"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_Q3
    name: ${power_meter_name_2}-Q3
    address: 0x001C
    unit_of_measurement: $unit_power_reactive
    device_class: "reactive_power"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
# ---------------------------- Phase voltage LL ------------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_L12
    name: ${power_meter_name_2}-L12
    address: 0x00C8
    unit_of_measurement: $unit_voltage
    device_class: "voltage"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_L23
    name: ${power_meter_name_2}-L23
    address: 0x00CA
    unit_of_measurement: $unit_voltage
    device_class: "voltage"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_L31
    name: ${power_meter_name_2}-L31
    address: 0x00CC
    unit_of_measurement: $unit_voltage
    device_class: "voltage"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
# ---------------------------- Neutral current -------------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_2}
    id: ${power_meter_id_2}_IN
    name: ${power_meter_name_2}-IN
    address: 0x00E0
    unit_of_measurement: $unit_current
    device_class: "current"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
