## Power meter: SDM72DM-V2 Grid total power(P,Q,S), energy
#
# Modbus RTU (rs485)
#
# vars:
#
#   - d<i>_modbus_controller_id
#   - d<i>_power_meter_id
#   - d<i>_power_meter_name
#
#VARS::
substitutions:
  modbus_controller_id: d<i>_modbus_controller_id
  power_meter_id: d<i>_power_meter_id
  power_meter_name: d<i>_power_meter_name

<<: !include ../units_estron.yaml 


sensor:
# ---------------------------- Total 3-phase ---------------------------
  - platform: modbus_controller
    modbus_controller_id: ${d<i>_modbus_controller_id}
    id: ${d<i>_power_meter_id}_system_P
    name: "${d<i>_power_meter_name}-P"
    address: 0x0034
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
    unit_of_measurement: ${unit_power_active}
    device_class: "power"
    state_class: "measurement"
  - platform: modbus_controller
    modbus_controller_id: ${d<i>_modbus_controller_id}
    id: ${d<i>_power_meter_id}_system_S
    name: "${d<i>_power_meter_name}-S"
    address: 0x0038
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
    unit_of_measurement: ${unit_power_apparent}
    device_class: "apparent_power"
    state_class: "measurement"
  - platform: modbus_controller
    modbus_controller_id: ${d<i>_modbus_controller_id}
    id: ${d<i>_power_meter_id}_system_Q
    name: "${d<i>_power_meter_name}-Q"
    address: 0x003C
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
    unit_of_measurement: ${unit_power_reactive}
    device_class: "reactive_power"
    state_class: "measurement"
  - platform: modbus_controller
    modbus_controller_id: ${d<i>_modbus_controller_id}
    id: ${d<i>_power_meter_id}_system_f
    name: "${d<i>_power_meter_name}-f"
    address: 0x0046
    unit_of_measurement: ${unit_frequency}
    device_class: "frequency"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
# ---------------------------- Energy Import/Export --------------------
  - platform: modbus_controller
    modbus_controller_id: ${d<i>_modbus_controller_id}
    id: ${d<i>_power_meter_id}_system_Eactive_import
    name: "${d<i>_power_meter_name}-Eactive_import"
    address: 0x0048
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
    unit_of_measurement: ${unit_energy}
    device_class: "energy"
    state_class: "total_increasing"
    filters:
      - multiply: 1000
  - platform: modbus_controller
    modbus_controller_id: ${d<i>_modbus_controller_id}
    id: ${d<i>_power_meter_id}_system_Eactive_export
    name: "${d<i>_power_meter_name}-Eactive_export"
    address: 0x004A
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
    unit_of_measurement: ${unit_energy}
    device_class: "energy"
    state_class: "total_increasing"
    filters:
      - multiply: 1000
# ---------------------------- Energy Active/Reactive (resetable) ------
  - platform: modbus_controller
    modbus_controller_id: ${d<i>_modbus_controller_id}
    id: ${d<i>_power_meter_id}_system_Eactive_resetable
    name: "${d<i>_power_meter_name}-Eactive_resetable"
    address: 0x0180
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
    unit_of_measurement: ${unit_energy}
    device_class: "energy"
    state_class: "total_increasing"
    filters:
      - multiply: 1000
  - platform: modbus_controller
    modbus_controller_id: ${d<i>_modbus_controller_id}
    id: ${d<i>_power_meter_id}_system_Ereactive_resetable
    name: "${d<i>_power_meter_name}-Ereactive_resetable"
    address: 0x0182
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
    unit_of_measurement: ${unit_energy}
    device_class: "energy"
    state_class: "total_increasing"
    filters:
      - multiply: 1000