## Power meter: SDM72DM-V2 Grid total power(P,Q,S), energy
#
# Modbus RTU (rs485)
#
# vars:
#
#   - modbus_controller_id
#   - power_meter_id
#   - power_meter_name
#


<<: !include ../units.yaml 


sensor:
# ---------------------------- Total 3-phase ---------------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_1}
    id: ${power_meter_id_1}_system_P
    name: "${power_meter_name_1}-P"
    address: 0x0034
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
    unit_of_measurement: ${unit_power_active_1}
    device_class: "power"
    state_class: "measurement"
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_1}
    id: ${power_meter_id_1}_system_S
    name: "${power_meter_name_1}-S"
    address: 0x0038
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
    unit_of_measurement: ${unit_power_apparent_1}
    device_class: "apparent_power"
    state_class: "measurement"
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_1}
    id: ${power_meter_id_1}_system_Q
    name: "${power_meter_name_1}-Q"
    address: 0x003C
    register_type: read
    value_type: FP32
    accuracy_decimals: 3
    unit_of_measurement: ${unit_power_reactive_1}
    device_class: "reactive_power"
    state_class: "measurement"
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_1}
    id: ${power_meter_id_1}_system_f
    name: "${power_meter_name_1}-f"
    address: 0x0046
    unit_of_measurement: ${unit_frequency_1}
    device_class: "frequency"
    state_class: "measurement"
    register_type: read
    value_type: FP32
    accuracy_decimals: 2
# ---------------------------- Energy Import/Export --------------------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_1}
    id: ${power_meter_id_1}_system_Eactive_import
    name: "${power_meter_name_1}-Eactive_import"
    address: 0x0048
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
    unit_of_measurement: ${unit_energy_1}
    device_class: "energy"
    state_class: "total_increasing"
    filters:
      - multiply: 1000
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_1}
    id: ${power_meter_id_1}_system_Eactive_export
    name: "${power_meter_name_1}-Eactive_export"
    address: 0x004A
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
    unit_of_measurement: ${unit_energy_1}
    device_class: "energy"
    state_class: "total_increasing"
    filters:
      - multiply: 1000
# ---------------------------- Energy Active/Reactive (resetable) ------
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_1}
    id: ${power_meter_id_1}_system_Eactive_resetable
    name: "${power_meter_name_1}-Eactive_resetable"
    address: 0x0180
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
    unit_of_measurement: ${unit_energy_1}
    device_class: "energy"
    state_class: "total_increasing"
    filters:
      - multiply: 1000
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_1}
    id: ${power_meter_id_1}_system_Ereactive_resetable
    name: "${power_meter_name_1}-Ereactive_resetable"
    address: 0x0182
    register_type: read
    value_type: FP32
    accuracy_decimals: 1
    unit_of_measurement: ${unit_energy_1}
    device_class: "energy"
    state_class: "total_increasing"
    filters:
      - multiply: 1000